name: Twitter Bot Check

on:
  schedule:
    - cron: '0 7,13,19 * * *' # TSİ 10:00, 16:00, 22:00
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Bağımlılıkları Yükle
        run: pip install requests

      - name: Botu Çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python bot.py

      - name: Durumu Kaydet
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          if [ -f last_tweets.json ]; then
            git add last_tweets.json
            git commit -m "Update state" || exit 0
            git push
          else
            echo "Dosya bulunamadı, commit atılmıyor."
          fi
